# Generated by Django 4.0.5 on 2022-07-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('E', 'Electronics'), ('C', 'Clothing'), ('A', 'Accessories')], max_length=2),
        ),
    ]
